In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
voc_size=10000

In [4]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2478, 1112, 792, 6470],
 [2478, 1112, 792, 9021],
 [2478, 2481, 792, 9606],
 [4901, 5954, 8031, 6686, 6318],
 [4901, 5954, 8031, 6686, 2208],
 [5544, 2478, 787, 792, 4764],
 [2507, 6880, 973, 6686]]

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [7]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2478 1112  792 6470]
 [   0    0    0    0 2478 1112  792 9021]
 [   0    0    0    0 2478 2481  792 9606]
 [   0    0    0 4901 5954 8031 6686 6318]
 [   0    0    0 4901 5954 8031 6686 2208]
 [   0    0    0 5544 2478  787  792 4764]
 [   0    0    0    0 2507 6880  973 6686]]


In [8]:
dim=10

In [9]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\SimpleRNN-IMDB\venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 196ms/step


array([[[-0.03202286, -0.00779208, -0.02962   , -0.02648703,
          0.03267291, -0.04199399, -0.0400211 , -0.03829651,
         -0.0423778 , -0.0299421 ],
        [-0.03202286, -0.00779208, -0.02962   , -0.02648703,
          0.03267291, -0.04199399, -0.0400211 , -0.03829651,
         -0.0423778 , -0.0299421 ],
        [-0.03202286, -0.00779208, -0.02962   , -0.02648703,
          0.03267291, -0.04199399, -0.0400211 , -0.03829651,
         -0.0423778 , -0.0299421 ],
        [-0.03202286, -0.00779208, -0.02962   , -0.02648703,
          0.03267291, -0.04199399, -0.0400211 , -0.03829651,
         -0.0423778 , -0.0299421 ],
        [ 0.02544696,  0.02801878,  0.03130469, -0.03417538,
          0.01112111, -0.02775451, -0.04811794,  0.04212913,
          0.02816227,  0.01558499],
        [ 0.04284019, -0.02090277, -0.02880687,  0.03643959,
         -0.02466379, -0.00251586, -0.0184261 ,  0.01103323,
          0.02371093,  0.01965347],
        [-0.0356141 , -0.00599375,  0.01297444, -0.0

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 2478, 1112,  792, 6470], dtype=int32)

In [14]:
import numpy as np

model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step


array([[[-0.03202286, -0.00779208, -0.02962   , -0.02648703,
          0.03267291, -0.04199399, -0.0400211 , -0.03829651,
         -0.0423778 , -0.0299421 ],
        [-0.03202286, -0.00779208, -0.02962   , -0.02648703,
          0.03267291, -0.04199399, -0.0400211 , -0.03829651,
         -0.0423778 , -0.0299421 ],
        [-0.03202286, -0.00779208, -0.02962   , -0.02648703,
          0.03267291, -0.04199399, -0.0400211 , -0.03829651,
         -0.0423778 , -0.0299421 ],
        [-0.03202286, -0.00779208, -0.02962   , -0.02648703,
          0.03267291, -0.04199399, -0.0400211 , -0.03829651,
         -0.0423778 , -0.0299421 ],
        [ 0.02544696,  0.02801878,  0.03130469, -0.03417538,
          0.01112111, -0.02775451, -0.04811794,  0.04212913,
          0.02816227,  0.01558499],
        [ 0.04284019, -0.02090277, -0.02880687,  0.03643959,
         -0.02466379, -0.00251586, -0.0184261 ,  0.01103323,
          0.02371093,  0.01965347],
        [-0.0356141 , -0.00599375,  0.01297444, -0.0